GET  http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczNTQzMTEsImV4cCI6MTY2NzM1NzkxMSwiYXVkIjoiNjM2MWFhODI2ZjdkZGQ1NmM1ZmNkZjVkIiwiaXNzIjoic2lka2kuY29tIn0.SCA4JI6lvwODlhAT_QwAs7Vrp0S0pJTx2QHs4TMC65
###login Route
POST http://localhost:3000/auth/login
content-type: application/json

{
"email": "sidki1@gmail.com",
"password":"1234"
}
###register Route
POST http://localhost:3000/auth/register
content-type: application/json

{
"email": "sidki1@gmail.com",
"password":"1234",
"role":"entreprise"
}
###Forget password
POST http://localhost:3000/auth/forgot-password
content-type: application/json

{
"email": "sidki1@gmail.com"
}

###Refresh token Route
POST http://localhost:3000/auth/refresh-token
###logout
DELETE http://localhost:3000/auth/logout
###Forget password
POST http://localhost:3000/auth/postarticle
content-type: application/json

{
"Photo": "https://images.unsplash.com/photo-1611915387288-fd8d2f5f928b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80",
"titre": "Ways to reduce ll",
"soustitre": "Get your own reusable bottle",
"description": "Learn how you can make small t",

"text": "You can put the reusable bottle to use  ",
"date":"Sunday 9 October 2022"

}

###logout
GET  http://localhost:3000/auth/getAllarticle