GET  http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczNTQzMTEsImV4cCI6MTY2NzM1NzkxMSwiYXVkIjoiNjM2MWFhODI2ZjdkZGQ1NmM1ZmNkZjVkIiwiaXNzIjoic2lka2kuY29tIn0.SCA4JI6lvwODlhAT_QwAs7Vrp0S0pJTx2QHs4TMC65
###login Route
POST http://localhost:3000/auth/login
content-type: application/json

{
"email": "sidki1@gmail.com",
"password":"1234"
}
###register Route
POST http://localhost:3000/auth/register
content-type: application/json

{
"email": "sidki1@gmail.com",
"password":"1234",
}
###Forget password
POST http://localhost:3000/auth/forgot-password
content-type: application/json

{
"email": "sidki1@gmail.com"
}

###Refresh token Route
POST http://localhost:3000/auth/refresh-token
###logout
DELETE http://localhost:3000/auth/logout

###validate email

POST http://localhost:3000/auth/validate-unique-email
content-type: application/json

{
}